(cl:in-package frcobot_hw-msg)
(cl:export '(HEADER-VAL
          HEADER
          FRAME_COUNT-VAL
          FRAME_COUNT
          PROGRAM_STATE-VAL
          PROGRAM_STATE
          ERROR_CODE-VAL
          ERROR_CODE
          ROBOT_MODE-VAL
          ROBOT_MODE
          CUR_JOINTS_POSE-VAL
          CUR_JOINTS_POSE
          CUR_TCP_POSE-VAL
          CUR_TCP_POSE
          CUR_JOINTS_TORQUE-VAL
          CUR_JOINTS_TORQUE
          TOOL_NUM-VAL
          TOOL_NUM
          CL_DGT_OUTPUT_H-VAL
          CL_DGT_OUTPUT_H
          CL_DGT_OUTPUT_L-VAL
          CL_DGT_OUTPUT_L
          TL_DGT_OUTPUT_L-VAL
          TL_DGT_OUTPUT_L
          ROBOT_MOTION_DONE-VAL
          ROBOT_MOTION_DONE
          GRIPPER_MOTION_DONE-VAL
          GRIPPER_MOTION_DONE
))